# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fd3ec91fa4174241f7e04edad8649461778288686e7e05bed6a1db83a448b46372d42aab83cffa16f3447fb9e1d6c1cb5b80566fb9c3d95a1c810fe7f70e094

test:
  secret_key_base: a9141562c52fe5282c68df05a57a5dfa2dbaf452bfe055bbb5a5c6b2ecadad7f56292a60424489c085f45ab10e6407a8319982d0deea7df445b7b556bb0cee21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
